apiVersion: v1
kind: Secret
metadata:
  name: {{ template "heimdall.fullname" . }}
  labels:
    {{- include "heimdall.labels" . | nindent 4 }}
type: Opaque
stringData:
 databaseUsername: {{ .Values.databaseUsername | quote }}
 databaseSslKey: {{ .Values.databaseSslKey | quote }}
 databaseSslCert: {{ .Values.databaseSslCert | quote }}
 databaseSslCa: {{ .Values.databaseSslCa | quote }}
 jwtSecret: {{ .Values.jwtSecret | quote }}
 apiKeySecret: {{ .Values.apiKeySecret | quote }}
 adminPassword: {{ .Values.adminPassword | quote }}
 githubClientId: {{ .Values.githubClientId | quote }}
 githubClientSecret: {{ .Values.githubClientSecret | quote }}
 gitlabClientId: {{ .Values.gitlabClientId | quote }}
 gitlabClientSecret: {{ .Values.gitlabClientSecret | quote }}
 googleClientId: {{ .Values.googleClientId | quote }}
 googleClientSecret: {{ .Values.googleClientSecret | quote }}
 oktaClientId: {{ .Values.oktaClientId | quote }}
 oktaClientSecret: {{ .Values.oktaClientSecret | quote }}
 oidcClientId: {{ .Values.oidcClientId | quote }}
 oidcClientSecret: {{ .Values.oidcClientSecret | quote }}
 ldapBindDn: {{ .Values.ldapBindDn | quote }}
 ldapPassword: {{ .Values.ldapPassword | quote }}
 ldapSslCa: {{ .Values.ldapSslCa | quote }}
data:
 databasePassword: {{ .Values.databasePassword | b64enc | quote }}
