apiVersion: v1
kind: Secret
metadata:
  name: {{ template "heimdall.fullname" . }}
  labels:
    {{- include "heimdall.labels" . | nindent 4 }}
type: Opaque
stringData:
 databaseUsername: {{ .Values.databaseUsername | quote }}
 databaseSslKey: {{ .Values.databaseSslKey | quote }}
 databaseSslCert: {{ .Values.databaseSslCert | quote }}
 databaseSslCa: {{ .Values.databaseSslCa | quote }}
 jwtSecret: {{ .Values.jwtSecret | quote }}
 apiKeySecret: {{ .Values.apiKeySecret | quote }}
 adminPassword: {{ .Values.adminPassword | quote }}
data:
 databasePassword: {{ .Values.databasePassword | b64enc | quote }}
