apiVersion: v1
kind: Secret
metadata:
  name: {{ template "heimdall.fullname" . }}
  labels:
    {{- include "heimdall.labels" . | nindent 4 }}
type: Opaque
stringData:
 databaseUsername: {{ .Values.databaseUsername | quote }} 
data:
 databasePassword: {{ .Values.databasePassword | b64enc | quote }}
 jwtSecret: {{ .Values.jwtSecret | quote }}  
